version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16.10.0 # Specify the Node.js version (use your preferred version here)
    commands:
      - echo Installing dependencies...
      - npm install  # Install Angular CLI and project dependencies
  build:
    commands:
      - npm run build --prod  # Build the Angular project for production
artifacts:
  files:
    - dist/**/*  # Upload the contents of the dist folder as the build artifacts
